# Generated by Django 4.2.23 on 2025-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_todolist_delete_todoitem_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isfavourite', models.BooleanField()),
            ],
        ),
    ]
